package proyectos.poo2022.chinchon.enumerados;

public enum EstadoPrograma {
	MENU,
	DESCARTAR_O_CERRAR,
	REGISTRANDO_JUGADOR,
	TOMANDO_CARTA,
	ESPERANDO_TURNO,
	ELIGIENDO_MAZO_O_PILA,
	FINALIZANDO_TURNO,
	PRUEBA,
	CERRANDO_RONDA,
	RECIBIENDO_CANTIDAD_JUGADAS,
	ARMANDO_1JUGADA,
	ARMANDO_2JUGADAS,
	RECIBIENDO_CARTA_QUE_CORTA,
	ESPERANDO_CONFIRMACION,
	MOSTRANDO_PUNTOS,
	PERDIO

}
