package proyectos.poo2022.chinchon.enumerados;

public enum EstadoPrograma {
	MENU,
	DESCARTAR,
	REGISTRANDO_JUGADOR, 
	TOMANDO_CARTA, 
	ESPERANDO_TURNO,
	RECIBIENDO_JUGADA_TURNO,
	FINALIZANDO_TURNO,
	PRUEBA,
	CERRANDO_RONDA,
	RECIBIENDO_CANTIDAD_JUGADAS, 
	ARMANDO_1JUGADA,
	ARMANDO_2JUGADAS,
	RECIBIENDO_CARTA_QUE_CORTA,
	ESPERANDO_CONFIRMACION,
	MOSTRANDO_PUNTOS,

}
