package proyectos.poo2022.chinchon.enumerados;

public enum Evento { 
	DESCARTAR, 
	CARTA_TOMADA,
	FIN_TURNO,
	TOMAR_CARTA_MAZO,
	TOMAR_CARTA_PILA_DESCARTE,
	CERRAR_PARTIDA,
	ARMAR_JUGADA,
	JUGADA_INVALIDA,
	JUGADA_VALIDA,
	CHINCHON,
	ENGANCHAR_JUEGO,
	NUEVO_TURNO,
	ACTUALIZAR_CARTAS, 
	INICIAR_PARTIDA,
	MOSTRAR_PUNTOS
	

}
